# Datasets are already TSV files
datasets:
  clean: ../contrib/test-data/clean.enzh.10

stages:
  - start

start:
  - clean  1
  - until clean 1

modifiers:
  - UpperCase: 0.2
  - TitleCase: 0.2
  - Tags: 0.1
    num_tags: 6
    custom_detok_src: null # Null value for the src detokenizer
    custom_detok_trg: zh

seed: 1111
trainer: cat
