# Datasets are already TSV files
datasets:
  clean: test-data/clean
  medium: test-data/medium
  dirty: test-data/dirty

stages:
  - start
  - mid
  - end

start:
  - clean  0.8
  - medium 0.2
  - dirty  0
  - until clean 2 # Until two epochs of clean

mid:
  - clean  0.6
  - medium 0.3
  - dirty  0.1
  - until medium 1

end:
  - clean  0.4
  - medium 0.3
  - dirty  0.3
  - until dirty 5 # use `inf` to mean until forever

modifiers:
  - uppercase:
    - probability: 0.05
  - titlecase:
    - probability: 0.05
  #- tags: # Requires dataset augmented with alignment info
  #  - probability: 0.08
  #  - num_tags: 6
  #  - custom_detok: zh
  #  - side trg # could be src, trg or both

seed: 1111
trainer: /usr/bin/cat
